spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order_management_db
    username: SM
    password: secret
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
